### ISSUE TITLE
Deployment script is not idempotent

### ISSUE THREAD

**Issue by rbrtwng** [cloudspannerecosystem/autoscaler#50] opened 2021-09-14 20:56 UTC
Following the steps to [Deploy a distributed Autoscaler tool for Cloud Spanner ](https://cloud.google.com/architecture/deploy-a-distributed-autoscaler-tool-for-cloud-spanner) and forgot to enable Cloud Scheduler API beforehand. 

Retried after enabling Cloud Scheduler API and it failed with the following error: 

```
module.forwarder.google_storage_bucket.bucket_gcf_source: Creating...
╷
│ Error: googleapi: Error 409: You already own this bucket. Please select another name., conflict
│
│   with module.forwarder.google_storage_bucket.bucket_gcf_source,
│   on ../../modules/forwarder/main.tf line 40, in resource "google_storage_bucket" "bucket_gcf_source":
│   40: resource "google_storage_bucket" "bucket_gcf_source" {
```

This indicates that the deployment script is not idempotent.

**Comment by henrybell** [comment] 2023-04-19 10:58
I’ve tried to reproduce this issue using the [most current instructions](https://github.com/cloudspannerecosystem/autoscaler/blob/master/terraform/cloud-functions/distributed/README.md) and following the steps described:

1. Ensure the Cloud Scheduler API is not enabled
1. Follow the directions for the distributed deployment model
1. Run Terraform and observe the failure in the App project
1. Enable the Cloud Scheduler API
1. Run Terraform again

Reproduction of the issue has not been possible and the second Terraform run completes successfully as shown in this Gist:

https://gist.github.com/henrybell/a5dc82d60d25851066c8037285819732

There has been a major restructuring of the repository since this issue was raised, plus updates to the versions of the Terraform provider(s) in use, and updates to the Terraform code itself. Because of this I am closing this issue – please reopen if you continue to experience the same failure.

**Closed by henrybell** 2023-04-19 10:58 UTC
Labels: backlog
