### ISSUE TITLE
setMetadata promise not triggering an error upon quota limits

### ISSUE THREAD

**Issue by itsdax** [cloudspannerecosystem/autoscaler#19] opened 2020-10-26 07:10 UTC
We are seeing an issue with a promise not triggering an error upon quota limits. Our calls all return without an error in the promise (We should see an error since this will fail due to insufficient quota). Our usage:

```
const spannerInstance = spannerClient.instance(spanner.instanceId);
  spannerInstance.setMetadata(metadata)
    .catch(err => {
      console.log("----- " + spanner.projectId + "/" + spanner.instanceId + ": Unsuccessful scaling attempt.\n\tThis may be caused by a previous ongoing scaling operation.");
      console.debug(err);
    });
```

However, this approach will successfully show the error:
```
spannerInstance.setMetadata(metadata, function(err, operation, apiResponse) {
    if (err) {
        console.log('err on func')
        return
    }
 
    operation
        .on('error',  function(err) {
                console.log(err)
        })
        .on('complete', function() {
                console.log('we finished!')
        });
  });
```

Output:
```
% node app.js
GoogleError: Project ************* cannot add 4 nodes in region us-central1.
    at Operation._unpackResponse (/Users/******/Desktop/projects/testjs/node_modules/google-gax/build
/src/longRunningCalls/longrunning.js:133:31)
    at /Users/*******/Desktop/projects/testjs/node_modules/google-gax/build/src/longRunningCalls/longr
unning.js:119:18 {
  code: 8
}
```

**Comment by davidcueva** [comment] 2020-11-03 12:18
Hi itsdax
Thanks for opening this issue. 
It seems you are using a previous version of the code. The call to `setMetadata()` now looks like:

```javascript
return spannerClient.instance(spanner.instanceId)
      .setMetadata(metadata)
      .then(function(data) {
        const operation = data[0];
        ...
```

The error handling is now done in a higher level function.
That being said, it is possible that the error you are observing is still not surfaced by the current code.
Therefore, could you please help us by trying the following:

1. Please update your code to its latest version.
2. Include the following line right after `const operation = data[0];` to capture the value returned as `operation`.

```javascript
        log("Operation Data:" + JSON.stringify(operation));
```

If the issue is still happening, please let us know and post the JSON printed by the added line.

Thanks,
David

**Comment by itsdax** [comment] 2020-11-12 01:56
I will update the version and try again. Thanks

**Comment by davidcueva** [comment] 2021-08-04 15:19
Hi itsdax, can you confirm the issue was resolved so I can close it?

**Closed** 2023-04-11 15:22 UTC
